services:
 
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    ports:
      - 8096:8096
      - 8920:8920
      - 1900:1900
      - 7359:7359
    volumes:
      - /config/jellyfin:/config
      - /cache/jellyfin:/cache
      - /data/podcasts:/media/Podcasts
      - /data/music:/media/Music
      - /data/music-videos:/media/MusicVideos
      - /data/videos:/media/Videos
