services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      WATCHTOWER_POLL_INTERVAL: 3600

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    stop_grace_period: 500s
    stop_signal: SIGINT
    ports:
      - "8096:8096/tcp"
#      - 8920:8920
#      - 1900:1900
#      - 7359:7359
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - jellyfin_media:/media

volumes:
  jellyfin_config:
    name: jellyfin_config
    external: true
  jellyfin_cache:
    name: jellyfin_cache
    external: true
  jellyfin_media:
    name: jellyfin_media
    external: true
